import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-admin-bill-datashowing',
  templateUrl: './admin-bill-datashowing.component.html',
  styleUrls: ['./admin-bill-datashowing.component.scss']
})
export class AdminBillDatashowingComponent implements OnInit {
  
  billAdmins = [
    {
      code: 'FS27042022',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Hà Bùi',
      address: '327/42 Lãnh Binh Thăng',
      district: '11',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS29052040',
      customer: 'LELAN',
      receiverName: 'Phúc',
      address: '59B Thạnh Xuân 33',
      district: '12',
      phoneNumber: '0909345678',
      customerNote: 'Không Cho Khách Xem Hàng - Nếu Khách Yêu Cầu Thì Liên Hệ Shop.',
      staffName: 'Tai',
      total: '220000',
      fee: '20000',
      advanceMoney: '200000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS29052044',
      customer: 'NGUYENTHU',
      receiverName: 'Ngọc Diệp',
      address: '18/9 Hà Thị Khiêm',
      district: '12',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '320000',
      fee: '20000',
      advanceMoney: '300000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS29052177',
      customer: 'NGUYENTHU',
      receiverName: 'Lan',
      address: '134/4 Lê Văn Khương',
      district: '12',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '450000',
      fee: '20000',
      advanceMoney: '430000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS29052071',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Xuân Kim',
      address: '171 Cao Thắng',
      district: '10',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS27042022',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Hà Bùi',
      address: '327/42 Lãnh Binh Thăng',
      district: '11',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS27042022',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Hà Bùi',
      address: '327/42 Lãnh Binh Thăng',
      district: '11',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS27042022',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Hà Bùi',
      address: '327/42 Lãnh Binh Thăng',
      district: '11',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
    {
      code: 'FS27042022',
      customer: 'KHOGACHIBUOI',
      receiverName: 'Hà Bùi',
      address: '327/42 Lãnh Binh Thăng',
      district: '11',
      phoneNumber: '0909345678',
      customerNote: 'Cho khách kiểm tra hàng. Hàng dễ vỡ xin nhẹ tay.',
      staffName: 'Tai',
      total: '180000',
      fee: '20000',
      advanceMoney: '160000',
      status: 'Chưa',
      staffNote: 'Khách không có ở nhà',
      doneDate: '21/04/2020',
    },
  ]
  constructor() { }

  ngOnInit() {
  }

}
